# Application configuration for H2 database
spring:
  application:
    name: contest-platform
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:contestdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Data Initialization
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      continue-on-error: true
      separator: ;
      encoding: UTF-8

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    com.shodh.contestplatform: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
